version: "3.8"

services:

    rabbitmq1:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq1
        hostname: rabbitmq1
        ports:
        networks: 
            - 15672:15672
            - rabbitmq_net
        volumes:
            - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=MNZMOGYCJXQJUFSAUYDY
    
    rabbitmq2:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq2
        hostname: rabbitmq2
        depends_on:
            - rabbitmq1
        ports:
            - 15673:15672
        networks: 
            - rabbitmq_net
        volumes:
            - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
            - ./config/rabbitmq2/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        environment:
            - RABBITMQ_ERLANG_COOKIE=MNZMOGYCJXQJUFSAUYDY
            
    rabbitmq3:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq3
        hostname: rabbitmq3
        depends_on: 
            - rabbitmq1
        ports:
            - 15674:15672
        networks:
            - rabbitmq_net
        volumes:
            - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
            - ./config/rabbitmq3/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        environment:
            - RABBITMQ_ERLANG_COOKIE=MNZMOGYCJXQJUFSAUYDY
    
    haproxy:
        image: haproxy-rabbitmq-cluster:1.7
        container_name: haproxy
        hostname: haproxy
        depends_on:
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3
        ports:
            - 5672:5672
            - 1936:1936
        networks:
            - rabbitmq_net
            
networks:
    rabbitmq_net:
        driver: bridge            
        